name: Simple Workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-16.04
    steps:
      - name: echo string
        run: echo "Hello"
      - name: check node version
        run: |
            node -v
            npm -v
            python --version
      - name: check python script 
        run: |
            import platform
            print(platform.processor())
        shell: python

  window-shell-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Default Shell (PowerShell)
        run: Get-Location
      - name: Bash Shell
        run: pwd
        shell: bash              
      - name: check node version
        run: |
            node -v
            npm -v
            python --version
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8            
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - run: |
          echo ${{ steps.setup-ndk.outputs.ndk-path }} > ./ndkpath.txt
