name: Simple Workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-16.04
    steps:
      - name: echo string
        run: echo "Hello"
      - name: check node version
        run: |
            node -v
            npm -v
            python --version
            which android            
      - name: check python script 
        run: |
            import platform
            print(platform.processor())
        shell: python

  window-shell-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Default Shell (PowerShell)
        run: Get-Location
      - name: Bash Shell
        run: pwd
        shell: bash              

